apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: IKKI League
  description: The IKKI League organization
  links:
    - url: https://ikki-league.com
      title: Website
spec:
  type: organization
  profile:
    displayName: IKKI League
    email: @example.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [infrastructure]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-groups
  description: A collection of all Backstage example Groups
spec:
  targets:
    - ./-squad-athena-group.yaml
    ---
