apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ikki-league
  description: The IKKI League organization
  links:
    - url: https://ikki-league.com
      title: Website
spec:
  type: organization
  profile:
    displayName: IKKI League
    email: ikki@ikki-league.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: ikki-groups
  description: A collection of all Backstage IKKI Groups
spec:
  targets:
    - ./squad-athena-group.yaml
    - ./squad-venus-group.yaml
